### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by M1ke** [kodus/sentry#10]
Is this repo maintained? If not how would the people who created it feel about either bringing me on as a maintainer, or allowing us to fork it and advertise the new fork on Packagist as the continuation?

There's some changes needed especially for PHP8 that are blocking our use case so I'd like to resolve these at least, as well as resolve my callable extension PR to add some more flexibility for middlewares.

**Comment by ghost** [comment]
Hi M1ke,
interesting question. I just started to use this alternative sentry client, because the original sentry PHP is too complicated to integrate into our project.. (tried for hours :-)

Now it seems it is not really maintained anymore... 

I was looking for solutions on how to add context to an captured event. Couldn't figure out how to do this...
There is a  addContext method in the Event Class, but from the outside when i use $sentry_client->captureException($e);
Also the method createEvent is protected and can't be called outside without modifiying the cource code. 
I might miss something here... 
How do i create an Event, add some info to it $event->addContext(bla). and then sent it out?
In my tests with sentry this was quite easy...
I can't figure out how to do this correctly in this client..
Any hint is highly appreciated..
Thanks!

**Comment by M1ke** [comment]
We've now forked this

https://github.com/sturents/sentry-light

Will continue to maintain the new version
